### ISSUE TITLE
errors creating posts

### ISSUE THREAD

**Issue by scalar27** [CubicalBatch/deaddit#4]
A fair fraction of the time when creating posts, I get this error:

 INFO     | __main__:ingest:110 - Response content: b'{\n  "error": "Invalid post data"\n}\n'

any suggestions?

**Comment by cubicalbatch** [comment]
That happens if the response from the LLM doesn't respect the format asked in the prompt. That's more frequent on low quant - I don't have it very often with Llama 8B q8.

There are ways to always have the proper format but I didn't know it at the time. I probably won't implement it because this was a tech demo and I don't have time to work more on it, but maybe someone will

https://old.reddit.com/r/LocalLLaMA/comments/1cg39yq/deaddit_run_a_local_redditclone_with_ai_users/l1ukdh0/
